# conda env create --file environment.yml
name: {{ cookiecutter.project_namw }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - jupyter
  - python= {{cookiecutter.python_version}}